## Data exploration and tidy data

### Objectives
* Tidy data, from theory to practice
* Exploring raw data
* Clean, tidy and preprocess the data

### Notes
* Online course resource in R [link](https://rmagno.eu/tdvr.oct.22/).

In [1]:
import os
import pandas as pd
from pandas.api.types import CategoricalDtype
import numpy as np

## 1. Raw data

In [35]:
# !rm -r 2025-tidy-python
!git clone https://github.com/Py-ualg/2025-tidy-python.git

Cloning into '2025-tidy-python'...
remote: Enumerating objects: 358, done.
remote: Counting objects: 100% (358/358), done.
remote: Compressing objects: 100% (346/346), done.
remote: Total 358 (delta 22), reused 338 (delta 11), pack-reused 0 (from 0)
Receiving objects: 100% (358/358), 6.63 MiB | 12.18 MiB/s, done.
Resolving deltas: 100% (22/22), done.

In [11]:
# alternative to download single files
# !wget https://github.com/Py-ualg/2025-tidy-python/blob/main/r2py/raw-data-python/2020-01-18_area1.csv

In [36]:
data_raw_path = '2025-tidy-python/r2py/raw-data-python/'

In [37]:
!ls

2020-01-18_area1.csv  2025-tidy-python	data-raw-python  sample_data

In [38]:
# quadrats01 <- readxl::read_excel(file.path(data_raw_path, "quadrats.xlsx"))
quadrats01  = pd.read_excel(os.path.join(data_raw_path, 'quadrats.xlsx'))
quadrats01.head()

  Unnamed: 0  Ria Formosa-rf  Ria Alvor-ra
0  Area (m2)             250           360

In [79]:
# df1_q1 <- readr::read_csv(file.path(data_raw_path, "2020-01-04_q1.csv"))
df1_ra = pd.read_csv(os.path.join(data_raw_path, '2020-01-04_ra.csv')).reset_index(drop=True)
# df1_rf <- readr::read_csv(file.path(data_raw_path, "2020-01-04_rf.csv"))
df1_rf = pd.read_csv(os.path.join(data_raw_path, '2020-01-04_rf.csv')).reset_index(drop=True)
df1_ra.head()

,Unnamed: 0,cl [cm],lcl [cm],fw [cm],species_name,longitude,is_gravid,rcl [cm],stage,sex,id,cw [cm],latitude,associated_species,depth [m],is_gravid?,behavior
0,0,17,5.644108,2,u. olhanen.,-7.99163,False,13.968383,adult,female,1,16.753110,37.01025,['Crab (Other Species)'],9,False,Slow movement near seagrass patches.
1,1,21,7.246445,2,u. olhanen.,NaN,True,4.064182,sub_adult,male,2,21.409872,NaN,"['Sea Sponge', 'Mussel']",9,True,Foraging among seagrass roots.
2,2,36,7.420922,3,A farensis,NaN,False,83.327000,juvenile,N/R,3,14.993753,NaN,"['Algae', 'Sea Star']",9,False,Interacting with small fish nearby.
3,3,48,6.222476,2,u. olhanen.,NaN,False,20.675049,sub_adult,male,4,19.416266,NaN,"['Jellyfish', 'Coral Fragment', 'Hermit Crab',...",7,False,Hiding under floating debris.
4,4,12,7.172794,6,A. Farensis,NaN,False,23.790701,pre_puberty,male,5,21.340372,NaN,"['Polychaete Worm', 'Sea Urchin', 'Snail', 'Se...",7,False,Climbing algae-covered rocks.

In [80]:
df1_ra.describe()

,Unnamed: 0,cl [cm],lcl [cm],fw [cm],longitude,rcl [cm],id,cw [cm],latitude,depth [m]
count,239.000000,239.00000,239.000000,239.000000,1.00000,239.000000,239.000000,239.000000,1.00000,239.000000
mean,119.000000,27.76569,6.375509,4.251046,-7.99163,33.061531,120.000000,18.990496,37.01025,8.020921
std,69.137544,12.43181,1.353753,2.040491,NaN,43.243369,69.137544,1.650741,NaN,2.023907
min,0.000000,8.00000,3.192399,2.000000,-7.99163,0.225523,1.000000,13.785196,37.01025,2.000000
25%,59.500000,19.00000,5.415769,3.000000,-7.99163,5.345980,60.500000,17.959630,37.01025,7.000000
50%,119.000000,25.00000,6.337956,4.000000,-7.99163,15.245565,120.000000,19.239509,37.01025,8.000000
75%,178.500000,35.00000,7.253392,6.000000,-7.99163,37.556066,179.500000,20.031597,37.01025,9.000000
max,238.000000,64.00000,10.164631,12.000000,-7.99163,191.567031,239.000000,22.558492,37.01025,13.000000

**Exercise**: remove the "Unnamed: 0" column

In [81]:
# prompt: remove "Unnamed: 0" column

df1_ra = df1_ra.drop('Unnamed: 0', axis=1)
df1_ra.head()

,cl [cm],lcl [cm],fw [cm],species_name,longitude,is_gravid,rcl [cm],stage,sex,id,cw [cm],latitude,associated_species,depth [m],is_gravid?,behavior
0,17,5.644108,2,u. olhanen.,-7.99163,False,13.968383,adult,female,1,16.753110,37.01025,['Crab (Other Species)'],9,False,Slow movement near seagrass patches.
1,21,7.246445,2,u. olhanen.,NaN,True,4.064182,sub_adult,male,2,21.409872,NaN,"['Sea Sponge', 'Mussel']",9,True,Foraging among seagrass roots.
2,36,7.420922,3,A farensis,NaN,False,83.327000,juvenile,N/R,3,14.993753,NaN,"['Algae', 'Sea Star']",9,False,Interacting with small fish nearby.
3,48,6.222476,2,u. olhanen.,NaN,False,20.675049,sub_adult,male,4,19.416266,NaN,"['Jellyfish', 'Coral Fragment', 'Hermit Crab',...",7,False,Hiding under floating debris.
4,12,7.172794,6,A. Farensis,NaN,False,23.790701,pre_puberty,male,5,21.340372,NaN,"['Polychaete Worm', 'Sea Urchin', 'Snail', 'Se...",7,False,Climbing algae-covered rocks.

This is typically not what you do in `pandas`, we shouw it here, because of R counterpart of `dplyr::glimpse(df1_ra)`, in python you typically do `df1_ra.head()`, however for wider tables, transposition is not a stupid idea.

In [82]:
# dplyr::glimpse(df1_ra), supposedly transposed print
df1_ra.T

,0,1,2,3,4,5,6,7,8,9,...,229,230,231,232,233,234,235,236,237,238
cl [cm],17,21,36,48,12,40,29,19,26,40,...,28,18,14,27,15,40,20,63,22,47
lcl [cm],5.644108,7.246445,7.420922,6.222476,7.172794,6.764107,4.851583,8.517339,5.379859,7.469099,...,6.869083,8.644844,4.711441,4.953529,7.440944,8.389032,7.313489,6.765991,6.516747,5.296869
fw [cm],2,2,3,2,6,7,9,2,5,7,...,4,5,2,6,3,9,2,4,2,2
species_name,u. olhanen.,u. olhanen.,A farensis,u. olhanen.,A. Farensis,A farensis,u. olhanen.,A farensis,A. Farensis,u. olhanen.,...,A. Farensis,A farensis,A. Farensis,A farensis,A. Farensis,u. olhanen.,A. Farensis,A farensis,A farensis,u. olhanen.
longitude,-7.99163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_gravid,False,True,False,False,False,True,False,False,False,False,...,False,True,False,True,False,False,True,True,False,True
rcl [cm],13.968383,4.064182,83.327,20.675049,23.790701,6.376075,3.254713,92.958957,33.559722,36.934159,...,54.000987,53.733938,3.030441,29.594919,158.424297,24.025581,10.867858,20.130964,17.627978,37.569287
stage,adult,sub_adult,juvenile,sub_adult,pre_puberty,sub_adult,sub_adult,pre_puberty,pre_puberty,adult,...,adult,sub_adult,pre_puberty,adult,sub_adult,pre_puberty,pre_puberty,sub_adult,sub_adult,pre_puberty
sex,female,male,N/R,male,male,?,female,?,male,male,...,,female,male,male,male,male,NaN,?,female,male
id,1,2,3,4,5,6,7,8,9,10,...,230,231,232,233,234,235,236,237,238,239
cw [cm],16.75311,21.409872,14.993753,19.416266,21.340372,18.400113,18.24738,15.45541,16.223398,18.392877,...,19.193923,18.604762,17.568035,20.17083,20.065549,17.622128,20.68924,17.267262,20.9238,21.047168
latitude,37.01025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
associated_species,['Crab (Other Species)'],"['Sea Sponge', 'Mussel']","['Algae', 'Sea Star']","['Jellyfish', 'Coral Fragment', 'Hermit Crab',...","['Polychaete Worm', 'Sea Urchin', 'Snail', 'Se...",['Sea Urchin'],"['Crab (Other Species)', 'Snail', 'Algae', 'Je...","['Mussel', 'Shrimp']","['Algae', 'Shrimp', 'Crab (Other Species)', 'S...","['Hermit Crab', 'Sea Star', 'Sea Anemone', 'Sh...",...,"['Snail', 'Sea Star', 'Small Fish']","['Mussel', 'Algae', 'Small Fish', 'Polychaete ...","['Sea Anemone', 'Sea Sponge', 'Sea Star']",['Small Fish'],"['Hermit Crab', 'Algae', 'Coral Fragment', 'Po...","['Hermit Crab', 'Shrimp', 'Sea Anemone', 'Sea ...","['Sea Sponge', 'Sea Anemone']","['Algae', 'Barnacle', 'Coral Fragment', 'Polyc...",['Jellyfish'],"['Jellyfish', 'Snail']"
depth [m],9,9,9,7,7,9,8,8,7,7,...,5,10,8,4,7,7,11,7,6,8
is_gravid?,False,True,False,False,False,True,False,False,False,False,...,False,True,False,True,False,False,True,True,False,True
behavior,Slow movement near seagrass patches.,Foraging among seagrass roots.,Interacting with small fish nearby.,Hiding under floating debris.,Climbing algae-covered rocks.,Inspecting discarded crab shell.,Mating behavior with antenna touching.,Rapid crossing of open sand.,Resting under shell fragment.,Slow movement near seagrass patches.,...,Color changes during molting.,Emerging cautiously from hiding.,Scavenging near tidal pools.,Hiding under seagrass blades.,Defensive posture when approached.,Displaying dominance by lifting body.,Guarding a small hole in sediment.,Searching for food in tidal pools.,Mating behavior with antenna touching.,Moving in groups.

In [83]:
# colnames(df1_ra)
df1_ra.columns  # index might be difficult to work with, get list by simply: list(df1_ra.columns)

Index(['cl [cm]', 'lcl [cm]', 'fw [cm]', 'species_name', 'longitude',
       'is_gravid', 'rcl [cm]', 'stage', 'sex', 'id', 'cw [cm]', 'latitude',
       'associated_species', 'depth [m]', 'is_gravid?', 'behavior'],
      dtype='object')

In [84]:
 # in R: (nrow() and ncol())
 df1_ra.shape

(239, 16)

In [85]:
# Value counts in column
# table(df1_ra$stage)
df1_ra['stage'].value_counts()

stage
sub_adult      87
pre_puberty    76
adult          46
juvenile       30
Name: count, dtype: int64

In [86]:
# Unique values in column
# unique(df1_ra$sex)
df1_ra['sex'].unique()

array(['female', 'male', 'N/R', '?', ' ', nan, 'male or female'],
      dtype=object)

## 2. Data tidying

In [87]:
# add region, and date
df1_ra['region'] = "Ria Formosa"
df1_ra['date'] = "2020-01-04"

df1_rf['region'] = "Ria Formosa"
df1_rf['date'] = "2020-01-04"

Check if the column names match for the datasets

In [88]:
set(df1_ra.columns) - set(df1_rf.columns)

{'behavior', 'is_gravid?', 'species_name'}

### Better and recommended way
- put `assert` checks everywhere you can
- the idea is to assert outputs, otherwise raise error

In [89]:
assert set(df1_ra.columns) == set(df1_rf.columns), f"Column names do not match {set(df1_ra.columns) - set(df1_rf.columns)}"

AssertionError: Column names do not match {'is_gravid?', 'species_name', 'behavior'}

Exercise: fix the column names

In [90]:
df1_ra.columns

Index(['cl [cm]', 'lcl [cm]', 'fw [cm]', 'species_name', 'longitude',
       'is_gravid', 'rcl [cm]', 'stage', 'sex', 'id', 'cw [cm]', 'latitude',
       'associated_species', 'depth [m]', 'is_gravid?', 'behavior', 'region',
       'date'],
      dtype='object')

In [91]:
df1_rf['region'] = "Ria Alvor"
df1_ra.rename(columns={"is_gravid?": "is_gravid", "species_name": "species", "behavior": "behaviour"}, inplace=True)

In [92]:
assert set(df1_ra.columns) == set(df1_rf.columns), f"Column names do not match {set(df1_ra.columns) - set(df1_rf.columns)}"

AssertionError: Column names do not match set()

In [93]:
df1_ra.columns

Index(['cl [cm]', 'lcl [cm]', 'fw [cm]', 'species', 'longitude', 'is_gravid',
       'rcl [cm]', 'stage', 'sex', 'id', 'cw [cm]', 'latitude',
       'associated_species', 'depth [m]', 'is_gravid', 'behaviour', 'region',
       'date'],
      dtype='object')

In [94]:
df1_rf.columns

Index(['Unnamed: 0', 'cl [cm]', 'lcl [cm]', 'fw [cm]', 'species', 'longitude',
       'is_gravid', 'rcl [cm]', 'stage', 'sex', 'id', 'cw [cm]', 'latitude',
       'associated_species', 'depth [m]', 'behaviour', 'region', 'date'],
      dtype='object')

In [95]:
df1_rf = df1_rf.drop('Unnamed: 0', axis=1)

In [96]:
assert set(df1_ra.columns) == set(df1_rf.columns), f"Column names do not match {set(df1_ra.columns) - set(df1_rf.columns)}"

Rename abbreviated columns which do not make sense to your student or a reviewer.

In [97]:
# rename all abbreviated columns
# df1_ra <- dplyr::rename(df1_ra, carapace_width = cw, carapace_length = cl, left_claw_length = lcl, right_claw_length = rcl, front_width = fw)

# Here I do it inplace to save code and space
df1_ra.rename(
    columns={
        "cw [cm]": "carapace_width",
        "cl [cm]": "carapace_length",
        "lcl [cm]": "left_claw_length",
        "rcl [cm]": "right_claw_length",
        'fw [cm]': 'front_width'},
    inplace=True,
)

In [98]:
df1_ra.head()

,carapace_length,left_claw_length,front_width,species,longitude,is_gravid,right_claw_length,stage,sex,id,carapace_width,latitude,associated_species,depth [m],is_gravid,behaviour,region,date
0,17,5.644108,2,u. olhanen.,-7.99163,False,13.968383,adult,female,1,16.753110,37.01025,['Crab (Other Species)'],9,False,Slow movement near seagrass patches.,Ria Formosa,2020-01-04
1,21,7.246445,2,u. olhanen.,NaN,True,4.064182,sub_adult,male,2,21.409872,NaN,"['Sea Sponge', 'Mussel']",9,True,Foraging among seagrass roots.,Ria Formosa,2020-01-04
2,36,7.420922,3,A farensis,NaN,False,83.327000,juvenile,N/R,3,14.993753,NaN,"['Algae', 'Sea Star']",9,False,Interacting with small fish nearby.,Ria Formosa,2020-01-04
3,48,6.222476,2,u. olhanen.,NaN,False,20.675049,sub_adult,male,4,19.416266,NaN,"['Jellyfish', 'Coral Fragment', 'Hermit Crab',...",7,False,Hiding under floating debris.,Ria Formosa,2020-01-04
4,12,7.172794,6,A. Farensis,NaN,False,23.790701,pre_puberty,male,5,21.340372,NaN,"['Polychaete Worm', 'Sea Urchin', 'Snail', 'Se...",7,False,Climbing algae-covered rocks.,Ria Formosa,2020-01-04

Now is the time we could merge all the data together, before continue the cleanup

**Exercise**:
Do the steps  from the above in the loop to merge all the datasets in `2025-tidy-python/r2py/raw-data-python/` folder.

In [99]:
# hidden help
from datetime import datetime

column_names = df1_ra.columns
column_names

Index(['carapace_length', 'left_claw_length', 'front_width', 'species',
       'longitude', 'is_gravid', 'right_claw_length', 'stage', 'sex', 'id',
       'carapace_width', 'latitude', 'associated_species', 'depth [m]',
       'is_gravid', 'behaviour', 'region', 'date'],
      dtype='object')

In [103]:
#@title Solution

from datetime import datetime

for file in os.listdir(data_raw_path):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(data_raw_path, file))
        df = df.drop('Unnamed: 0', axis=1)
        df.rename(
            columns={
                "cw [cm]": "carapace_width",
                "cl [cm]": "carapace_length",
                "lcl [cm]": "left_claw_length",
                "rcl [cm]": "right_claw_length",
                'fw [cm]': 'front_width'},
            inplace=True,
        )
        if '_ra.csv' in file:
            df['region'] = "Ria Alvor"
        else:
            df['region'] = "Ria Formosa"
        date = file.split('_')[0]
        df['date'] = pd.to_datetime(date) # Convert to datetime object

        try:
            df.rename(columns={"is_gravid?": "is_gravid", "species_name": "species", "behavior": "behaviour"}, inplace=True)
        except:
            pass


        assert set(column_names) == set(df.columns), f"Column names do not match {set(df.columns) - set(column_names)}"
        df[['latitude', 'longitude']] = df[['latitude', 'longitude']].ffill()

In [104]:
df.head()

,carapace_length,left_claw_length,front_width,species,longitude,is_gravid,right_claw_length,stage,sex,id,carapace_width,latitude,associated_species,depth [m],behaviour,region,date
0,12,7.444669,2,A. Farensis,-8.01873,False,2.443310,sub_adult,female,1,13.029304,37.02606,"['Snail', 'Sea Anemone', 'Algae', 'Coral Fragm...",8,Camouflaging with surrounding mud.,Ria Formosa,2020-04-06
1,17,5.313689,2,A. Farensis,-8.01873,True,5.770629,adult,male,2,15.999848,37.02606,"['Sea Sponge', 'Algae', 'Crab (Other Species)'...",10,Foraging among seagrass roots.,Ria Formosa,2020-04-06
2,12,5.137900,6,U. olhanensis,-8.01873,False,25.265988,sub_adult,male,3,13.815169,37.02606,"['Shrimp', 'Snail', 'Sea Anemone', 'Polychaete...",4,Rapid claw movement while feeding.,Ria Formosa,2020-04-06
3,15,7.496274,3,A farensis,-8.01873,False,1.494236,juvenile,male,4,13.071705,37.02606,"['Jellyfish', 'Sea Urchin']",9,Retreating into burrow.,Ria Formosa,2020-04-06
4,18,4.499608,3,A. Farensis,-8.01873,False,6.203628,adult,male,5,16.364347,37.02606,"['Sea Urchin', 'Jellyfish', 'Barnacle', 'Snail']",9,Resting under shell fragment.,Ria Formosa,2020-04-06

TODO:
* multiply ra data by 10 as if measured in mm in raw data
* Hide one -999 value into a  numeric column
* replace adult, sub_adult, juvenile by j, a, s